#!/usr/bin/env perl
#
# Copyright (C) 2024 Michael Daum http://michaeldaumconsulting.com
#
# For licensing info read LICENSE file in the Foswiki root.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html

use strict;
use warnings;

# Set library paths in @INC, at compile time
BEGIN {
  if (-e './setlib.cfg') {
    unshift @INC, '.';
  } elsif (-e '../bin/setlib.cfg') {
    unshift @INC, '../bin';
  }
  $Foswiki::cfg{Engine} = 'Foswiki::Engine::CLI';
  require 'setlib.cfg';
}

use Foswiki ();
use Foswiki::Request ();
use Foswiki::Contrib::RcsFastStoreContrib ();
use Foswiki::Contrib::VirtualHostingContrib::VirtualHost ();


my $verbose = 1;
my $hostname = '';
my $query;

my %args = ();
foreach my $arg (@ARGV) {
  if ($arg =~ /^(.*)=(.*)$/) {
    $args{$1} = $2;

    if ($1 eq 'verbose') {
      $verbose = ($2 eq 'on')?1:0;
    } elsif ($1 eq 'host') {
      $hostname = $2;
    }
  } 
}

if ($hostname) {
  Foswiki::Contrib::VirtualHostingContrib::VirtualHost->run_on($hostname, \&doit);
} else {
  Foswiki::Contrib::VirtualHostingContrib::VirtualHost->run_on_each(\&doit);
}


sub doit {
  printf("=> Processing %s\n", $Foswiki::Contrib::VirtualHostingContrib::VirtualHost::CURRENT) if $verbose;

  $args{topic} //= ($Foswiki::cfg{HomeWebName} // $Foswiki::cfg{UsesWebName}).'.'.$Foswiki::cfg{HomeTopicName};

  my $req = Foswiki::Request->new(\%args);
  my $foswiki = Foswiki->new('admin', $req);

  Foswiki::Contrib::RcsFastStoreContrib::checkStore($foswiki);

  $foswiki->finish();
}

1;
